---
name: "Test Add-on"
description: "Testing purpose add-on"
version: "0.0.1"
slug: "domiot_test"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ingress: true
panel_title: "Test Add-on"

options:
  core_addon_hostname: ""
schema:
  core_addon_hostname: str
