---
name: "Example Add-on"
description: "My first real add-on!"
version: "0.0.1"
slug: "example_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
options:
  core_addon_hostname: ""
schema:
  core_addon_hostname: str
