---
all:
  hosts:
    homeassistant:
      ansible_host: "{{ lookup('env', 'HA_IP') | default('127.0.0.1', true) }}"
      ansible_port: 2222
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3