"""2

Revision ID: 2798a17d32ff
Revises: dee36ae51265
Create Date: 2025-04-23 16:33:09.706537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2798a17d32ff'
down_revision = 'dee36ae51265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_day', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('all_day')

    # ### end Alembic commands ###
